### ISSUE TITLE
synced_files problem

### ISSUE THREAD

**Issue by steffenk** [Tuurlijk/TYPO3.Homestead#41]
Hi Michiel,

tested your box with synced_files option. I use this config:

```
 synced_folders:
  - name: Development
    src: ~/Development/web/sites/Homestead
    target: /var/www
```

but instead rsyncing the files in this dir, i only get the vagrant dir of Homestead synced to /vagrant. Running box with latest vagrant and macos sierra.

Any hints what i'm doing wrong?

Greets
